version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ./DjDevOps/DjDevOps/settings/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dj-network
    # healthcheck :
    #   test: [ "CMD", "pg_isready", "-q", "-d", "usersdb"]
    #   interval : 10s
    #   timeout : 5s
    #   retries : 5


  web-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: web-app
    env_file: 
      - ./DjDevOps/DjDevOps/settings/.env
    volumes:
      - static_files:/home/app/webapp/static
    ports:
      - "8000:8000"
    depends_on: 
      - db
    restart: always
    networks:
      - dj-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:
  static_files:

networks:
  dj-network:
