name: Pipeline that Build and Push the docker app image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: itachi44/dj-devops:${{ steps.current_date.outputs.date }}
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }} 
            POSTGRES_USER=${{ secrets.POSTGRES_USER }} 
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} 
            DATABASE_PROD_HOST=${{ secrets.DATABASE_PROD_HOST }} 
            POSTGRES_DB=${{ secrets.POSTGRES_DB }} 
            PRODUCTION_SECRET_KEY=${{ secrets.PRODUCTION_SECRET_KEY }} 
            ENV_MODE=${{ secrets.ENV_MODE }} 
            SECRET_KEY=${{ secrets.SECRET_KEY }} 

      - name: Push Docker image to registry
        run: |
          docker push itachi44/dj-devops:${{ steps.current_date.outputs.date }}