name: Pipeline that Build and Push the docker app image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Generate .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ./DjDevOps/DjDevOps/settings/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./DjDevOps/DjDevOps/settings/.env
          echo "DATABASE_PROD_HOST=${{ secrets.DATABASE_PROD_HOST }}" >> ./DjDevOps/DjDevOps/settings/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./DjDevOps/DjDevOps/settings/.env
          echo "SECRET_KEY=${{ secrets.PRODUCTION_SECRET_KEY }}" >> ./DjDevOps/DjDevOps/settings/.env
          echo "ENV_MODE=${{ secrets.ENV_MODE }}" >> ./DjDevOps/DjDevOps/settings/.env


      - name: Build Docker Compose images
        run: |
          docker-compose up -d --build --force-recreate
          docker images

      # - name: push the database service
      #   run: |
      #     docker tag "dj-devops_db" "${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:db-$DOCKER_TAG"
      #     docker push "${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:db-$DOCKER_TAG"

      - name: Tag and push web-app image
        run: |
          IMAGE_ID="djangodevops_web-app"
          DOCKER_TAG="${{ github.run_number }}"
          REPO_NAME="dj-devops"
          docker tag "$IMAGE_ID" "${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:$DOCKER_TAG"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:$DOCKER_TAG"

      # - name: Run a simple test to ensure the application loads correctly
      #   run: |
      #     python ./DjDevOps/manage.py test